# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_Title', models.CharField(blank=True, default=b'', max_length=500)),
                ('SNR_AvailableAt', models.CharField(blank=True, default=b'', max_length=200)),
                ('SNR_Description', models.CharField(blank=True, default=b'', max_length=5000)),
                ('SNR_Type', models.CharField(blank=True, default=b'Trending', max_length=200)),
                ('SNR_Category', models.CharField(blank=True, default=b'mobile', max_length=200)),
                ('SNR_PriceMin', models.CharField(blank=True, default=b'', max_length=20)),
                ('SNR_PriceMax', models.CharField(blank=True, default=b'', max_length=20)),
                ('SNR_ProductURL', models.CharField(blank=True, default=b'', max_length=3000)),
                ('SNR_ImageURL', models.CharField(blank=True, default=b'', max_length=3000)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='trends',
            unique_together=set([('SNR_Title', 'SNR_ImageURL', 'SNR_ProductURL')]),
        ),
    ]
