# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trends',
            unique_together=set([('SNR_Title', 'SNR_ImageURL', 'SNR_ProductURL', 'SNR_PriceMax')]),
        ),
    ]
