# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pp_subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_age', models.IntegerField()),
                ('psd1', models.FloatField()),
                ('psd3', models.FloatField()),
                ('psd6', models.FloatField()),
                ('psd10', models.FloatField()),
            ],
        ),
    ]
